config/routes.rb
Syllabi::Application.routes.draw do
  resources :topics
  resources :syllabuses
  root 'topics#index'
  match '/about',   to: 'static_pages#about', via: 'get'

end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
  belongs_to :topic
  validates_presence_of :topic_id, :title, :chnm_cache
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  has_many :syllabuses
  validates :name, presence:true, uniqueness: true
  validates_presence_of :slug
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController

  def index
    @syllabuses = Syllabus.paginate(page: params[:page], :per_page => 3)
  end

  def new
    @syllabus = Syllabus.new
  end

  def show
    @syllabus = Syllabus.find(params[:id])
  end

  def create
    @syllabus = Syllabus.new(params[syllabus_params])
    if @syllabus.save
      redirect_to @syllabus
    else
      render 'new'
    end

  end

  def destroy
    Syllabus.find(params[:id]).destroy
    flash[:success] = "Syllabus deleted."
    redirect_to root_url
  end

  def update
    @syllabus = Syllabus.find(params[:id])
    if @syllabus.update_attributes(syllabus_params)
      flash[:success] = "Syllabus updated"
      redirect_to @syllabus
    else
      redirect_to @syllabus
    end
  end

  private

    def syllabus_params
      params.require(:syllabus).permit(:url, :chnm_cache, :topic_id, :title)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topics = Topic.all
    @topic = Topic.friendly.find(params[:id])
    @syllabuses = @topic.syllabuses.paginate(page: params[:page], :per_page => 3)
  end

  def create
    @topic = Topic.new(params[topic_params])
    if @topic.save
      redirect_to @topic
    else
      render 'new'
    end
  end

  def new
    @topic = Topic.new
  end

  def destroy
    Topic.friendly.find(params[:id]).destroy
    flash[:success] = "Topic deleted."
    redirect_to root_url
  end

  def index
    @topics = Topic.all
  end

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/syllabuses_helper.rb
module SyllabusesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <i>Open</i>Syllabus
  </small>
  <nav>
    <ul>
        <%= render 'layouts/nav' %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <nav>
      <ul class="nav pull-right">
        <%= render 'layouts/nav' %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_nav.html.erb
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "About", about_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenSyllabus</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
        <%= yield %>
        <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<row>
  <div class="span8 offset2">
    <h1>
      About
    </h1>

    <p>In <a href="http://www.dancohen.org/2011/03/30/a-million-syllabi/">A Million Syllabi</a>,
    Dan Cohen released a database of over a million syllabi gathered by his Syllabus Finder tool.
    However, only 1% of the syllabi in the database were cached.</p>

    <p>By scraping the URLs in the database, we hope to provide a publicly available indexable
    and searchable repository of all the syllabi on the internet.</p>

    <p>Currently collected out of 1.5 million syllabi:</p>

    <div class="progress">
      <div class="progress-bar" role="progressbar" aria-valuenow="12" aria-valuemin="0" aria-valuemax="100" style="width: 12%">
        <span class="sr-only">12% Complete (success)</span>
      </div>
    </div>

  </div>
</row>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/syllabuses/_syllabus.html.erb
<li>
  <h1><%=syllabus.title%></h1>
  <p></p>In <%= link_to syllabus.topic.name, topic_path(syllabus.topic) %>

  <a data-toggle="collapse" href="#topicForm">(change)</a>

  <p><div id="topicForm" class="collapse">
  <%= form_for syllabus do |f| %>
      <p><%= f.select :topic_id, options_from_collection_for_select(Topic.all, :id, :name)%></p>
      <p><%= f.submit "Save changes", class: "btn btn-primary" %></p>
  <% end %>
</div>   </p>

  <%= link_to '(source)', syllabus.url %>
  <%= raw(syllabus.chnm_cache) %>
</li>

app/views/syllabuses/create.html.erb
<h1>Syllabuses#create</h1>
<p>Find me in app/views/syllabuses/create.html.erb</p>

app/views/syllabuses/destroy.html.erb
<h1>Syllabuses#destroy</h1>
<p>Find me in app/views/syllabuses/destroy.html.erb</p>

app/views/syllabuses/index.html.erb
<div class="row">
  <aside class="span2">
    sidebar
  </aside>
  <div class="span8 mainscroll">
    <%= will_paginate %>

    <ul class="syllabuses">
      <% @syllabuses.each do |syllabus| %>
          <%= render syllabus %>
      <% end %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

app/views/syllabuses/new.html.erb
<h1>Syllabuses#new</h1>
<p>Find me in app/views/syllabuses/new.html.erb</p>

app/views/syllabuses/show.html.erb
<row>
  <div class="span8 offset2">
    <%= render 'syllabus', syllabus: @syllabus %>
  </div>
</row>
<row>

</row>

app/views/syllabuses/update.html.erb
<h1>Syllabuses#update</h1>
<p>Find me in app/views/syllabuses/update.html.erb</p>

app/views/topics/_topic.html.erb
<li><%= link_to topic.name, topic_path(topic)  %></li>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/index.html.erb
<div class="mainpage center hero-unit">
  <h1><i>Open</i>Syllabus</h1>
  <div class="btn-group">
    <button type="button" class="btn btn-large dropdown-toggle" data-toggle="dropdown">
      What would you like to learn about? <span class="caret"></span>
    </button>
    <ul class="dropdown-menu pull-right" role="menu">
      <% @topics.each do |topic| %>
          <%= render topic %>
      <% end %>
    </ul>
  </div>

</div>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<div class="row">
  <aside class="span2">
    <h1>Topics</h1>
    <section>
      <ul class="topicList">
        <% @topics.each do |topic| %>
            <%= render topic %>
        <% end %>
      </ul>
    </section>
  </aside>

  <div class="span8 mainscroll">
    <h1><%= @topic.name %></h1>
    <%= will_paginate @syllabuses %>

    <ul class="syllabuses">
      <% @syllabuses.each do |syllabus| %>
          <%= render syllabus %>
      <% end %>
    </ul>

    <%= will_paginate @syllabuses %>
  </div>
</div>